import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { OAuthIdentitySchema, type OAuthIdentity } from "@knowledge-ai/contracts";

export type GoogleOAuthErrorCode="DISABLED"|"INVALID_STATE"|"PROVIDER_FAILURE";
export class GoogleOAuthError extends Error { constructor(readonly code:GoogleOAuthErrorCode){super(code==="DISABLED"?"Google authentication is not configured":code==="INVALID_STATE"?"Google authentication state is invalid":"Google authentication failed");this.name="GoogleOAuthError";} }
export interface GoogleOAuthConfig {clientId:string;clientSecret:string;redirectUri:string;authorizationEndpoint:string;tokenEndpoint:string;userInfoEndpoint:string;}
interface Options {fetch?:typeof fetch;createState?:()=>string;createVerifier?:()=>string;}
function equal(left:string,right:string){const a=Buffer.from(left);const b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
export class GoogleOAuthAdapter {
  readonly enabled:boolean; private readonly providerFetch:typeof fetch; private readonly createState:()=>string; private readonly createVerifier:()=>string;
  constructor(private readonly config:GoogleOAuthConfig|null,options:Options={}){this.enabled=Boolean(config);this.providerFetch=options.fetch??fetch;this.createState=options.createState??(()=>randomBytes(32).toString("base64url"));this.createVerifier=options.createVerifier??(()=>randomBytes(48).toString("base64url"));}
  createAuthorization(){if(!this.config)throw new GoogleOAuthError("DISABLED");const state=this.createState();const verifier=this.createVerifier();const challenge=createHash("sha256").update(verifier).digest("base64url");const url=new URL(this.config.authorizationEndpoint);url.search=new URLSearchParams({client_id:this.config.clientId,redirect_uri:this.config.redirectUri,response_type:"code",scope:"openid email profile",state,code_challenge:challenge,code_challenge_method:"S256",prompt:"select_account"}).toString();return{url:url.toString(),state,verifier};}
  async exchange(input:{code:string;state:string;expectedState:string;verifier:string}):Promise<OAuthIdentity>{if(!this.config)throw new GoogleOAuthError("DISABLED");if(!equal(input.state,input.expectedState))throw new GoogleOAuthError("INVALID_STATE");try{const tokenResponse=await this.providerFetch(this.config.tokenEndpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",code:input.code,client_id:this.config.clientId,client_secret:this.config.clientSecret,redirect_uri:this.config.redirectUri,code_verifier:input.verifier})});if(!tokenResponse.ok)throw new Error("token");const token=await tokenResponse.json() as {access_token?:unknown};if(typeof token.access_token!=="string")throw new Error("token");const profileResponse=await this.providerFetch(this.config.userInfoEndpoint,{headers:{Authorization:`Bearer ${token.access_token}`}});if(!profileResponse.ok)throw new Error("profile");const profile=await profileResponse.json() as {sub?:unknown;email?:unknown;email_verified?:unknown;name?:unknown};if(profile.email_verified!==true)throw new Error("unverified");return OAuthIdentitySchema.parse({provider:"google",subject:profile.sub,email:typeof profile.email==="string"?profile.email.toLowerCase():profile.email,displayName:profile.name});}catch(error){if(error instanceof GoogleOAuthError)throw error;throw new GoogleOAuthError("PROVIDER_FAILURE");}}
}
